# Generated by Django 4.2.1 on 2023-07-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="car_features",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Cruise Control", "Cruise Control"),
                    ("Audio Interface", "Audio Interface"),
                    ("Airbags", "Airbags"),
                    ("Air Conditioning", "Air Conditioning"),
                    ("Seat Heating", "Seat Heating"),
                    ("ParkAssist", "ParkAssist"),
                    ("Power Steering", "Power Steering"),
                    ("Reversing Camera", "Reversing Camera"),
                    ("Auto Start/Stop", "Auto Start/Stop"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
