# Generated by Django 4.2.1 on 2023-06-01 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("carapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyer",
            name="phone_number",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="area",
            field=models.CharField(
                choices=[
                    ("W", "Windsor"),
                    ("LS", "LaSalle"),
                    ("A", "Amherstburg"),
                    ("L", "Lakeshore"),
                    ("LE", "Leamington"),
                    ("CH", "Chatham"),
                ],
                default="CH",
                max_length=2,
            ),
        ),
        migrations.CreateModel(
            name="OrderVehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_of_Vehicles", models.IntegerField(default=0)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], default=0
                    ),
                ),
                ("order_date", models.DateField()),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="carapp.buyer"
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="carapp.vehicle"
                    ),
                ),
            ],
        ),
    ]
