# Generated by Django 4.2.1 on 2023-06-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carapp", "0002_buyer_phone_number_alter_buyer_area_ordervehicle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="area",
            field=models.CharField(
                choices=[
                    ("W", "Windsor"),
                    ("LS", "LaSalle"),
                    ("A", "Amherstburg"),
                    ("L", "Lakeshore"),
                    ("LE", "Leamington"),
                    ("CH", "Chatham"),
                    ("T", "Toronto"),
                ],
                default="CH",
                max_length=2,
            ),
        ),
    ]
