# Generated by Django 4.2.1 on 2023-06-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carapp", "0004_alter_buyer_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="car_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
