# Generated by Django 4.2.1 on 2023-06-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carapp", "0005_alter_vehicle_car_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="description",
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
