# Generated by Django 4.2.1 on 2023-06-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carapp", "0006_vehicle_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordervehicle",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "cancelled"),
                    (1, "placed"),
                    (2, "shipped"),
                    (3, "delivered"),
                ],
                default=0,
            ),
        ),
    ]
