# Generated by Django 4.2.1 on 2023-06-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carapp", "0007_alter_ordervehicle_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Description",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("projectD", models.TextField(blank=True, max_length=500)),
                ("description_date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
