# Generated by Django 4.2.1 on 2023-06-07 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carapp", "0009_alter_description_description_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="description",
            old_name="description_date",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="description", old_name="projectD", new_name="project",
        ),
    ]
